[package]
edition = "2021"
license = "Apache-2.0"
name = "mdbook-prql"
repository = "https://github.com/prql/prql"
rust-version = "1.59.0"
version = "0.1.1"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", default-features = false }
globset = "0.4.8"
insta = { version = "1.14.0", features = ["colors", "glob"] }
itertools = "0.10.3"
mdbook = { version = "0.4.18", default-features = false }
mdbook-preprocessor-boilerplate = "0.1.1"
prql-compiler = {path = "../../prql-compiler"}
pulldown-cmark = "0.9.1"
pulldown-cmark-to-cmark = "10.0.1"
semver = "1.0.9"
serde_json = "1.0.81"
similar = "2.1.0"
walkdir = "2.3.2"
