[package]
authors = ["Kasun Vithanage <kasvith.me@gmail.com>"]
description = "Elixir NIF bindings for prql-compiler"
# TODO: Update to 2021
edition = "2018"
# TODO: should this be `prql-elixir`?
name = "prql"
publish = false

# edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "prql"
path = "src/lib.rs"

[dependencies]
prql-compiler = {path = "../../../prql-compiler", default-features = false, version = "0.4.2"}
rustler = "0.26.0"
