version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      # Running daily means the GHA cache will be cycling much faster, and we're
      # not in a great rush. So trying weekly, and we can iterate.
      interval: weekly
    commit-message:
      prefix: "chore: "
    # Bump all patch versions of rust dependencies as a single PR
    groups:
      patch:
        update-types:
          - patch
    # We exclude labels throughout because of https://github.com/dependabot/dependabot-core/issues/7645#issuecomment-1986212847
    labels: []

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore: "
    labels: []

  - package-ecosystem: "npm"
    directory: "/prqlc/bindings/js"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    commit-message:
      prefix: "chore: "
    labels: []

  - package-ecosystem: "npm"
    directory: "/web/playground"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    commit-message:
      prefix: "chore: "
    labels: []

  - package-ecosystem: docker
    directory: .devcontainer/base-image
    schedule:
      interval: daily
    commit-message:
      prefix: "chore: "
    labels: []

  - directory: ".github/actions/build-python"
    commit-message:
      prefix: "chore: "
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    labels: []

  - directory: ".github/actions/build-prqlc"
    commit-message:
      prefix: "chore: "
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    labels: []

  - directory: ".github/actions/time-compilation"
    commit-message:
      prefix: "chore: "
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    labels: []

  - package-ecosystem: pip
    directory: "prqlc/bindings/prqlc-python"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore: "
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    labels: []

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
    labels: []
