[files]
extend-exclude = [
  "web/book/theme/highlight.js",
  "prqlc/prqlc/tests/integration/data/",
  "prqlc/prqlc/tests/integration/snapshots/",
  "web/website/themes/prql-theme/static/plugins/bootstrap",
  "web/website/themes/prql-theme/static/plugins/highlight/highlight.min.js",
]

[default.extend-words]
# <itemDatas> in grammars/KSyntaxHighlighting/prql.xml
datas = "datas"
# Java test framework
testng = "testng"
# Readme highlighting the first characters of these words
anguage = "anguage"
elational = "elational"
ipelined = "ipelined"
uery = "uery"
# `wee-alloc` is a crate name
wee = "wee"
flate = "flate"
