[package]
name = "prqlc-c"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# This means we can build with `--features=default`, which can make builds more generic
[features]
default = []

[lib]
# We produce both of these at the moment, but could consider refining this. ref
# https://github.com/rust-lang/cargo/issues/8607 &
# https://github.com/rust-lang/rust/issues/59302
crate_type = ["staticlib", "cdylib"]
doctest = false
test = false
doc = false

[dependencies]
libc = "0.2.155"
prqlc = {path = "../../prqlc", default-features = false}
serde_json = "1.0.117"

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""
