[package]
description = "Javascript bindings for prqlc"
name = "prqlc-js"
publish = false
rust-version = "1.73.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doc = false
doctest = false
test = false

[features]
default = ["console_error_panic_hook"]

[target.'cfg(target_family="wasm")'.dependencies]
prqlc = {path = "../../prqlc", default-features = false}
wasm-bindgen = "0.2.93"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. While the docs state that "This is great
# for development, but requires all the `std::fmt` and `std::panicking`
# infrastructure, so isn't great for code size when deploying.", on testing with
# `--no-default-features`,
# `prql/target/wasm32-unknown-unknown/release/prqlc_js.wasm` is 7.416MB vs
# 7.408MB. Maybe because we're already including lots of that with other library
# features? Even running `wasm-opt prqlc_js.wasm` makes similarly sized files of
# 5.7M. Feel free to try removing this as part of reducing code size (would be
# good to have a much smaller code size...).
console_error_panic_hook = {version = "0.1.7", optional = true}

[target.'cfg(target_family="wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3.43"

[package.metadata.cargo-udeps.ignore]
development = ["wasm-bindgen-test"]

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""

[[package.metadata.release.pre-release-replacements]]
exactly = 1
file = "package.json"
replace = '$1"{{version}}"'
search = '(  "version": )"(\d+\.\d+\.\d+)"'

[[package.metadata.release.pre-release-replacements]]
exactly = 2
file = "package-lock.json"
replace = '$1"{{version}}"'
search = '''
(\s+"prqlc",
\s+"version": )"[\d\.]+"'''

[[package.metadata.release.pre-release-replacements]]
exactly = 1
file = "../../../web/playground/package.json"
replace = '$1"{{version}}"'
search = '(  "version": )"(\d+\.\d+\.\d+)"'

[[package.metadata.release.pre-release-replacements]]
exactly = 2
file = "../../../web/playground/package-lock.json"
replace = '$1"{{version}}"'
search = '''
(\s+"prql-playground",
\s+"version": )"[\d\.]+"'''

[[package.metadata.release.pre-release-replacements]]
exactly = 1
file = "../../../web/playground/package-lock.json"
replace = '$1"{{version}}"'
search = '''
(".*/prqlc/bindings/js": \{
\s+"name":.*
\s+"version": )"[\d\.]+"'''
