[book]
description = "Modern language for transforming data â€” a simple, powerful, pipelined SQL replacement"
language = "en"
title = "PRQL language book"

[output.html]
additional-css = ["comparison-table.css"]
additional-js = ["highlight-prql.js"]
git-repository-url = "https://github.com/PRQL/prql"

[preprocessor.prql]
# This is required because mdbook-prql isn't necessarily installed; maybe
# there's a better way.
#
command = "cargo run --bin mdbook-prql"

[preprocessor.footnote]
