baseURL: "https://prql-lang.org/"
languageCode: en-us
title: PRQL
theme: prql-theme

disableKinds:
  - taxonomy
  - term

enableGitInfo: true

menu:
  nav:
    # TODO: Can we use the info from pages directly? https://gohugo.io/templates/menu-templates/#menu-entries-from-the-pages-front-matter
    - identifier: Docs
      name: Docs
      url: /book/
      weight: 1
    - identifier: Playground
      name: Playground
      url: /playground/
      weight: 2
    - identifier: Roadmap
      name: Roadmap
      url: /roadmap/
      weight: 3
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 4
    - identifier: FAQ
      name: FAQ
      url: /faq/
      weight: 5

params:
  contribute:
    subtitle: |
      Contribute to PRQL — we're a welcoming community, and there are lots of ways to make an impact:

    list:
      - text:
          Are there people whose opinion you respect who might be interested in
          PRQL? Send them a link to PRQL.
      - text:
          "Know Rust (or want to learn!)? [Contribute to our
          compiler](https://prql-lang.org/book/project/contributing/#compiler)"
      - text:
          "Familiar with web? Spot a mistake? [Improve the website design or
          copy](https://prql-lang.org/book/project/contributing/#marketing)"
      - text:
          "Interested in helping people explore their data? [Help improve the
          playground](https://github.com/PRQL/prql/tree/main/web/playground)"
      - text:
          "Is SQL your mother-tongue? [Show us SQL queries which translate well
          /
          badly](https://prql-lang.org/book/project/contributing/#language-design).
          We are looking for any use-cases that expose a poor design choice, a
          need of a feature, or a sharp edge of the language."
    button:
      text: Contribute
      link: https://prql-lang.org/book/project/contributing/
  follow:
    subtitle: "Follow us:"
    list:
      - text: Star our GitHub repo [PRQL/prql](https://github.com/PRQL/prql)
      - text: Join our [Discord](https://discord.com/invite/eQcfaCmsNc)
      - text: Follow us on [Twitter](https://twitter.com/prql_lang)
  description: PRQL is a modern language for transforming data
  images:
    - static/img/favicon-32x32.png
  title: PRQL

  license: "© 2022-2024, PRQL Developers. Apache 2.0 Licensed"

googleAnalytics: G-LQJDD599T4