[package]
build = "build.rs"
name = "lutra-python"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "lutra"

[target.'cfg(not(target_family="wasm"))'.dependencies]
# we rename lutra to lutralib here, so we can define a function named lutra
lutralib = { package = "lutra", path = "../../lutra", default-features = false }
arrow = { version = "49.0", features = ["pyarrow"], default-features = false }
itertools = "0.12.0"
pyo3 = { version = "0.20.2", features = ["abi3-py37", "anyhow"] }

[build-dependencies]
pyo3-build-config = "0.20.0"

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""
