[package]
authors = ["Kasun Vithanage <kasvith.me@gmail.com>"]
description = "Elixir NIF bindings for prqlc"
name = "prql"
publish = false
rust-version = "1.73.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = ["cdylib"]
doc = false
doctest = false
name = "prql"
path = "src/lib.rs"
test = false

# See Readme for details on Mac
[target.'cfg(not(any(target_family="wasm", target_os = "macos")))'.dependencies]
prqlc = {path = "../../../../prqlc", default-features = false, version = "0.13.1" }
rustler = "0.34.0"
