[package]
name = "prqlc-clib"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "prqlc" 
crate_type = ["staticlib", "cdylib"]
doctest = false
test = false

[dependencies]
libc = "0.2"
prql-compiler = {path = "../../prql-compiler", default-features = false}
serde_json = "1.0"

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""
