[package]
build = "build.rs"
description = "Python bindings for prqlc"
name = "prqlc-python"
publish = false
rust-version = "1.73.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = ["cdylib"]
doc = false
doctest = false

[target.'cfg(not(target_family="wasm"))'.dependencies]
pyo3 = {workspace = true}

[dependencies]
# Renamed to avoid conflicts in lib.rs
prqlc_lib = {package = "prqlc", path = "../../prqlc", default-features = false}

[dev-dependencies]
insta = {workspace = true}

[build-dependencies]
pyo3-build-config = {workspace = true}

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""

# We want the package to be named `prqlc`, but the crate is named `prqlc-python`
# to avoid a conflict with other cargo artifacts. This option renames the
# package to `prqlc`.
[package.metadata.maturin]
name = "prqlc"
