[package]
description = "The AST for the PRQL language."
name = "prqlc-ast"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
doctest = false

[dependencies]
enum-as-inner = "0.6.0"
semver = {version = "1.0.20", features = ["serde"]}
serde = {version = "1.0.188", features = ["derive"]}
strum = {version = "0.25.0", features = ["std", "derive"]}
