name: publish
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable

      # website
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.5.0
      - name: Build website
        run: hugo --minify
        working-directory: website/

      # reference
      - name: ðŸ’° Cache
        uses: Swatinem/rust-cache@v1
      - uses: peaceiris/actions-mdbook@v1
      - name: ðŸ”¨ Build reference
        run: mdbook build
        working-directory: reference/

      # webapp
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json
      - run: npm ci
        working-directory: webapp/
      - run: npm run build
        working-directory: webapp/

      - name: Move reference and webapp into website
        run: |
          mv reference/book website/public/reference
          mv webapp/build website/public/compiler
      - name: ðŸš¢ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public/

  build-python-wheels:
    uses: ./.github/workflows/python.yaml
  publish-to-pypi:
    name: Release
    runs-on: ubuntu-latest
    # Currently excluded since we need to use the PYPI_API_TOKEN
    # if: "startsWith(github.ref, 'refs/tags/')"
    if: false
    needs: [build-python-wheels]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          # TODO: Upload PYPI_API_TOKEN, confirm how we release all crates together.
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
