name: publish
on:
  push:
    branches:
      - main
    tags:
      - "*"
  # Called by pull-request when specifically requested
  workflow_call:

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable

      # website
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.5.0
      - name: Build website
        run: hugo --minify
        working-directory: website/

      # book
      - name: ðŸ’° Cache
        uses: Swatinem/rust-cache@v1
      - uses: peaceiris/actions-mdbook@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-admonish
          version: v1.7.0
      - name: ðŸ”¨ Build book
        run: mdbook build
        working-directory: book/

      # playground
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: playground/package-lock.json
      - run: npm ci
        working-directory: playground/
      - run: npm run build
        working-directory: playground/

      - name: Move book and playground into website
        run: |
          mv book/book website/public/book
          mv playground/build website/public/playground
      - name: ðŸš¢ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public/
