name: pull-request-target

on:
  pull_request_target:
    types: [opened, edited, synchronize, labeled, closed]

concurrency:
  # Generally we use `github.ref`, but in pull_request_target, that's always `main`.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          # The standard ones plus
          # - "internal" for code quality / ergonomics improvements
          # - "devops" for developer ergonomics
          # - "web" for playground / website (but not docs)
          # - "tweak" for tiny changes
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

            internal
            devops
            web
            tweak

  backport:
    # Backport to `web` branch on `pr-backport-web`
    name: Backport to `web` branch
    runs-on: ubuntu-latest
    # Confirm that it's merged and has a label to ensure nothing is backported without oversight
    if: |
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'pr-backport-web')
        )
      )
    steps:
      - uses: tibdex/backport@v2
        with:
          # This is a personal access token from the @prql-bot
          github_token: ${{ secrets.BACKPORT_GITHUB_TOKEN }}
          # Docs are at https://github.com/tibdex/backport/blob/main/action.yml
          # We only use `website` atm
          label_pattern: "^pr-backport-(?<base>([^ ]+))$"
          title_template: "chore: Backport #<%= number%> to `web`"
