name: test-php

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "prql-php/**"
      - ".github/workflows/test-php.yaml"
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: ./prql-php
    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies using Composer
        uses: php-actions/composer@v6
        with:
          php_extensions: FFI
#      - name: PHPUnit Tests
#        uses: php-actions/phpunit@v3
#        with:
#          php_extensions: FFI
