# Runs cargo test & cargo lint for a given platform.

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
      target:
        type: string
        # default:

jobs:
  test_and_lint_2:
    runs-on: ${{ inputs.os }}
    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v2
      - name: ğŸ’° Cache
        uses: Swatinem/rust-cache@v1
      - name: ğŸ› ï¸ Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: ğŸ“ Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --workspace -- -D warnings
      # Note that `--all-targets` doesn't refer to targets like `wasm32-unknown-unknown`. So we need another step here.
      - name: ğŸ”— Setup rust wasm toolchain
        if: ${{ inputs.target }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - name: âŒ¨ï¸ Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
      - name: ğŸ“‹ Test
        uses: actions-rs/cargo@v1
        with:
          command: test
