name: test-js

on:
  workflow_call:
    inputs:
      oss:
        type: string
        default: "[ubuntu-latest]"
  workflow_dispatch:
    inputs:
      oss:
        type: string
        default: "[ubuntu-latest]"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-js
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: ${{ fromJSON(inputs.oss) }}
        os: ["ubuntu-latest"]
    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wasm-pack

      - run: npm cit
        working-directory: bindings/prql-js
