[package]
description = "The AST for the PRQL language."
name = "prqlc-ast"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["anyhow"]

[lib]
doctest = false

[dependencies]
anyhow = {version = "1.0.79", optional = true}
enum-as-inner = "0.6.0"
semver = {version = "1.0.20", features = ["serde"]}
serde = {version = "1.0.193", features = ["derive"]}
strum = {version = "0.26.1", features = ["std", "derive"]}

[dev-dependencies]
insta = "1.34"
serde_json = "1.0.109"
